// OpenSpace App - Complete Styles
const styles = {
  // ===========================================
  // CONTAINER & LAYOUT
  // ===========================================
  container: {
    minHeight: '100vh',
    background: '#f8fafc',
    position: 'relative',
    maxWidth: 430,
    margin: '0 auto',
    fontFamily: "'DM Sans', -apple-system, BlinkMacSystemFont, sans-serif",
  },
  backgroundGradient: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 300,
    background: 'linear-gradient(135deg, #e0e7ff 0%, #fae8ff 50%, #fce7f3 100%)',
    zIndex: 0,
  },

  // ===========================================
  // HEADER
  // ===========================================
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '16px 20px',
    position: 'relative',
    zIndex: 1,
  },
  logoContainer: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
  },
  logoIcon: {
    width: 36,
    height: 36,
    borderRadius: 10,
    background: 'linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'white',
  },
  logoText: {
    fontSize: 22,
    fontWeight: 700,
    color: '#1e293b',
    letterSpacing: '-0.5px',
  },
  headerRight: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
  },
  notificationBtn: {
    position: 'relative',
    background: 'white',
    border: 'none',
    borderRadius: 12,
    width: 44,
    height: 44,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    boxShadow: '0 2px 8px rgba(0,0,0,0.06)',
  },
  notificationDot: {
    position: 'absolute',
    top: 10,
    right: 10,
    width: 8,
    height: 8,
    background: '#ef4444',
    borderRadius: '50%',
    border: '2px solid white',
  },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: 12,
    background: 'linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'white',
    fontWeight: 600,
    fontSize: 16,
  },

  // ===========================================
  // NAVIGATION
  // ===========================================
  navPills: {
    display: 'flex',
    gap: 8,
    padding: '0 20px 16px',
    position: 'relative',
    zIndex: 1,
    overflowX: 'auto',
  },
  navPill: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    padding: '10px 16px',
    background: 'rgba(255,255,255,0.7)',
    border: 'none',
    borderRadius: 20,
    fontSize: 14,
    fontWeight: 500,
    color: '#64748b',
    cursor: 'pointer',
    whiteSpace: 'nowrap',
    transition: 'all 0.2s',
  },
  navPillActive: {
    background: 'white',
    color: '#1e293b',
    boxShadow: '0 2px 8px rgba(0,0,0,0.08)',
  },

  // ===========================================
  // MAIN CONTENT
  // ===========================================
  main: {
    padding: '0 20px 100px',
    position: 'relative',
    zIndex: 1,
  },
  greeting: {
    marginBottom: 16,
  },
  greetingText: {
    fontSize: 20,
    fontWeight: 600,
    color: '#1e293b',
  },
  pageTitle: {
    fontSize: 26,
    fontWeight: 700,
    color: '#1e293b',
    marginBottom: 4,
  },
  pageSubtitle: {
    fontSize: 15,
    color: '#64748b',
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 600,
    color: '#1e293b',
    marginBottom: 16,
  },

  // ===========================================
  // CARDS
  // ===========================================
  card: {
    background: 'white',
    borderRadius: 20,
    padding: 24,
    marginBottom: 16,
    boxShadow: '0 4px 20px rgba(0,0,0,0.06)',
  },
  cardHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    marginBottom: 16,
  },
  checkInIcon: {
    width: 32,
    height: 32,
    borderRadius: 10,
    background: '#ecfdf5',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkInLabel: {
    flex: 1,
    fontSize: 14,
    color: '#64748b',
  },
  moreBtn: {
    background: 'none',
    border: 'none',
    color: '#94a3b8',
    cursor: 'pointer',
    fontSize: 16,
    letterSpacing: 2,
  },
  advisorRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 14,
    marginBottom: 12,
  },
  advisorAvatar: {
    width: 52,
    height: 52,
    borderRadius: 14,
    background: 'linear-gradient(135deg, #ccfbf1 0%, #99f6e4 100%)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  advisorName: {
    fontSize: 17,
    fontWeight: 600,
    color: '#1e293b',
  },
  advisorSubtext: {
    fontSize: 14,
    color: '#64748b',
  },
  dateRow: {
    display: 'flex',
    alignItems: 'baseline',
    gap: 10,
    marginBottom: 16,
  },
  dateHighlight: {
    fontSize: 18,
    fontWeight: 600,
    color: '#6366f1',
  },
  timeText: {
    fontSize: 15,
    color: '#64748b',
  },
  recommendText: {
    fontSize: 14,
    color: '#64748b',
    marginBottom: 20,
    lineHeight: 1.5,
  },

  // ===========================================
  // BUTTONS
  // ===========================================
  secondaryBtn: {
    width: '100%',
    padding: '14px 20px',
    background: 'transparent',
    border: 'none',
    borderRadius: 12,
    fontSize: 15,
    fontWeight: 600,
    color: '#1e293b',
    cursor: 'pointer',
    marginBottom: 10,
  },
  primaryBtn: {
    width: '100%',
    padding: '14px 20px',
    background: 'linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%)',
    border: 'none',
    borderRadius: 12,
    fontSize: 15,
    fontWeight: 600,
    color: 'white',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 12,
    background: 'rgba(255,255,255,0.8)',
    border: 'none',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
  },

  // ===========================================
  // SNAPSHOT CARD
  // ===========================================
  snapshotCard: {
    background: 'white',
    borderRadius: 20,
    padding: 24,
    marginBottom: 16,
    boxShadow: '0 4px 20px rgba(0,0,0,0.06)',
  },
  snapshotHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    marginBottom: 20,
  },
  snapshotTitle: {
    fontSize: 16,
    fontWeight: 600,
    color: '#1e293b',
  },
  snapshotGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: 16,
    marginBottom: 16,
  },
  snapshotItem: {
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
  },
  snapshotLabel: {
    fontSize: 13,
    color: '#64748b',
  },
  snapshotValue: {
    fontSize: 20,
    fontWeight: 600,
    color: '#cbd5e1',
  },
  snapshotHint: {
    fontSize: 13,
    color: '#94a3b8',
    textAlign: 'center',
    fontStyle: 'italic',
  },

  // ===========================================
  // TASKS
  // ===========================================
  tasksSection: {
    background: 'white',
    borderRadius: 20,
    padding: 20,
    boxShadow: '0 4px 20px rgba(0,0,0,0.06)',
  },
  tasksHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    marginBottom: 16,
    paddingBottom: 16,
    borderBottom: '1px solid #f1f5f9',
  },
  tasksTitle: {
    fontSize: 16,
    fontWeight: 600,
    color: '#1e293b',
  },
  tasksList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
  },
  taskItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 14,
    padding: '14px 0',
    background: 'none',
    border: 'none',
    borderBottom: '1px solid #f1f5f9',
    cursor: 'pointer',
    textAlign: 'left',
    width: '100%',
  },
  taskCheck: {
    width: 24,
    height: 24,
  },
  taskCheckEmpty: {
    width: 22,
    height: 22,
    borderRadius: 6,
    border: '2px solid #e2e8f0',
  },
  taskCheckComplete: {
    width: 22,
    height: 22,
    borderRadius: 6,
    background: '#10b981',
    color: 'white',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 12,
    fontWeight: 700,
  },
  taskInfo: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
  },
  taskName: {
    fontSize: 15,
    fontWeight: 500,
    color: '#1e293b',
  },
  taskNameComplete: {
    textDecoration: 'line-through',
    color: '#94a3b8',
  },
  taskUrgent: {
    fontSize: 13,
    color: '#f59e0b',
    fontWeight: 500,
  },
  taskPending: {
    fontSize: 13,
    color: '#94a3b8',
  },
  taskComplete: {
    fontSize: 13,
    color: '#10b981',
    fontWeight: 500,
  },

  // ===========================================
  // BOTTOM NAVIGATION
  // ===========================================
  bottomNav: {
    position: 'fixed',
    bottom: 0,
    left: '50%',
    transform: 'translateX(-50%)',
    width: '100%',
    maxWidth: 430,
    background: 'white',
    display: 'flex',
    justifyContent: 'space-around',
    padding: '12px 20px 24px',
    borderTop: '1px solid #f1f5f9',
    zIndex: 100,
  },
  bottomNavItem: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 4,
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    position: 'relative',
  },
  bottomNavLabel: {
    fontSize: 12,
    color: '#94a3b8',
    fontWeight: 500,
  },
  messageBadge: {
    position: 'absolute',
    top: -2,
    right: 4,
    width: 18,
    height: 18,
    background: '#ef4444',
    borderRadius: '50%',
    color: 'white',
    fontSize: 11,
    fontWeight: 600,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },

  // ===========================================
  // FLOATING HELP
  // ===========================================
  floatingHelp: {
    position: 'fixed',
    bottom: 100,
    right: 20,
    width: 56,
    height: 56,
    borderRadius: '50%',
    background: 'linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%)',
    border: 'none',
    boxShadow: '0 4px 20px rgba(99, 102, 241, 0.4)',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 99,
  },

  // ===========================================
  // ONBOARDING CONTAINER
  // ===========================================
  onboardingContainer: {
    minHeight: '100vh',
    background: '#f8fafc',
    position: 'relative',
    maxWidth: 430,
    margin: '0 auto',
    fontFamily: "'DM Sans', -apple-system, BlinkMacSystemFont, sans-serif",
    display: 'flex',
    flexDirection: 'column',
  },
  onboardingGradient: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 200,
    background: 'linear-gradient(135deg, #e0e7ff 0%, #fae8ff 50%, #fce7f3 100%)',
    zIndex: 0,
  },
  onboardingHeader: {
    display: 'flex',
    alignItems: 'center',
    padding: '16px 20px',
    position: 'relative',
    zIndex: 1,
    gap: 16,
  },
  progressContainer: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 6,
  },
  progressBar: {
    width: '100%',
    height: 6,
    background: 'rgba(255,255,255,0.5)',
    borderRadius: 3,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    background: 'linear-gradient(90deg, #6366f1 0%, #8b5cf6 100%)',
    borderRadius: 3,
    transition: 'width 0.3s ease',
  },
  progressText: {
    fontSize: 12,
    color: '#64748b',
    fontWeight: 500,
  },
  onboardingMain: {
    flex: 1,
    padding: '0 20px',
    position: 'relative',
    zIndex: 1,
    overflowY: 'auto',
    paddingBottom: 120,
  },
  onboardingFooter: {
    position: 'fixed',
    bottom: 0,
    left: '50%',
    transform: 'translateX(-50%)',
    width: '100%',
    maxWidth: 430,
    padding: '20px',
    background: 'linear-gradient(180deg, transparent 0%, #f8fafc 20%)',
    zIndex: 10,
  },
  continueBtn: {
    width: '100%',
    padding: '16px 24px',
    background: 'linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%)',
    border: 'none',
    borderRadius: 14,
    fontSize: 16,
    fontWeight: 600,
    color: 'white',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    boxShadow: '0 4px 20px rgba(99, 102, 241, 0.3)',
  },

  // ===========================================
  // STEP CONTENT
  // ===========================================
  stepContent: {
    paddingTop: 20,
  },
  stepTitle: {
    fontSize: 26,
    fontWeight: 700,
    color: '#1e293b',
    marginBottom: 8,
    letterSpacing: '-0.5px',
  },
  stepSubtitle: {
    fontSize: 16,
    color: '#64748b',
    marginBottom: 32,
    lineHeight: 1.5,
  },

  // ===========================================
  // FORM ELEMENTS
  // ===========================================
  formGroup: {
    marginBottom: 28,
  },
  label: {
    display: 'block',
    fontSize: 15,
    fontWeight: 600,
    color: '#1e293b',
    marginBottom: 12,
  },
  labelHint: {
    fontSize: 13,
    color: '#94a3b8',
    marginTop: -8,
    marginBottom: 12,
  },
  input: {
    width: '100%',
    padding: '16px 18px',
    background: 'white',
    border: '2px solid #e2e8f0',
    borderRadius: 14,
    fontSize: 16,
    color: '#1e293b',
    outline: 'none',
    transition: 'border-color 0.2s',
    boxSizing: 'border-box',
  },
  textarea: {
    width: '100%',
    padding: '16px 18px',
    background: 'white',
    border: '2px solid #e2e8f0',
    borderRadius: 14,
    fontSize: 16,
    color: '#1e293b',
    outline: 'none',
    resize: 'none',
    fontFamily: 'inherit',
    boxSizing: 'border-box',
  },
  textareaLarge: {
    width: '100%',
    padding: '18px 20px',
    background: 'white',
    border: '2px solid #e2e8f0',
    borderRadius: 16,
    fontSize: 16,
    color: '#1e293b',
    outline: 'none',
    resize: 'none',
    fontFamily: 'inherit',
    lineHeight: 1.6,
    boxSizing: 'border-box',
  },

  // ===========================================
  // SLIDER
  // ===========================================
  sliderContainer: {
    display: 'flex',
    alignItems: 'center',
    gap: 16,
    background: 'white',
    padding: '16px 20px',
    borderRadius: 14,
    border: '2px solid #e2e8f0',
  },
  slider: {
    flex: 1,
    height: 6,
    borderRadius: 3,
    appearance: 'none',
    background: '#e2e8f0',
    outline: 'none',
  },
  sliderValue: {
    fontSize: 15,
    fontWeight: 600,
    color: '#6366f1',
    minWidth: 80,
    textAlign: 'right',
  },

  // ===========================================
  // OPTION BUTTONS
  // ===========================================
  optionGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: 10,
  },
  optionBtn: {
    padding: '14px 16px',
    background: 'white',
    border: '2px solid #e2e8f0',
    borderRadius: 12,
    fontSize: 14,
    fontWeight: 500,
    color: '#64748b',
    cursor: 'pointer',
    transition: 'all 0.2s',
    textAlign: 'center',
  },
  optionBtnActive: {
    background: '#f0f0ff',
    borderColor: '#6366f1',
    color: '#6366f1',
  },
  optionRow: {
    display: 'flex',
    gap: 12,
  },
  optionBtnLarge: {
    flex: 1,
    padding: '18px 20px',
    background: 'white',
    border: '2px solid #e2e8f0',
    borderRadius: 14,
    fontSize: 15,
    fontWeight: 600,
    color: '#64748b',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },

  // ===========================================
  // CHECKBOX GRID
  // ===========================================
  checkboxGrid: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
  },
  checkboxBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    padding: '14px 16px',
    background: 'white',
    border: '2px solid #e2e8f0',
    borderRadius: 12,
    fontSize: 15,
    color: '#64748b',
    cursor: 'pointer',
    transition: 'all 0.2s',
    textAlign: 'left',
  },
  checkboxBtnActive: {
    background: '#f0f0ff',
    borderColor: '#6366f1',
    color: '#6366f1',
  },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    border: '2px solid #e2e8f0',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 14,
    fontWeight: 700,
    color: '#6366f1',
    background: 'white',
    flexShrink: 0,
  },
  checkboxActive: {
    background: '#6366f1',
    borderColor: '#6366f1',
    color: 'white',
  },

  // ===========================================
  // GOAL BUTTONS
  // ===========================================
  goalGrid: {
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
  },
  goalBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: 14,
    padding: '16px 18px',
    background: 'white',
    border: '2px solid #e2e8f0',
    borderRadius: 14,
    cursor: 'pointer',
    transition: 'all 0.2s',
    textAlign: 'left',
    position: 'relative',
  },
  goalBtnActive: {
    background: '#f0f0ff',
    borderColor: '#6366f1',
  },
  goalIcon: {
    fontSize: 24,
  },
  goalLabel: {
    flex: 1,
    fontSize: 15,
    fontWeight: 500,
    color: '#1e293b',
  },
  goalCheck: {
    width: 24,
    height: 24,
    borderRadius: 12,
    background: '#6366f1',
    color: 'white',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 14,
    fontWeight: 700,
  },

  // ===========================================
  // COUNTER
  // ===========================================
  counterRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 24,
    background: 'white',
    padding: '16px',
    borderRadius: 14,
    border: '2px solid #e2e8f0',
  },
  counterBtn: {
    width: 44,
    height: 44,
    borderRadius: 12,
    background: '#f1f5f9',
    border: 'none',
    fontSize: 24,
    color: '#64748b',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  counterValue: {
    fontSize: 28,
    fontWeight: 700,
    color: '#1e293b',
    minWidth: 40,
    textAlign: 'center',
  },

  // ===========================================
  // COMFORT OPTIONS
  // ===========================================
  comfortOptions: {
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
  },
  comfortBtn: {
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
    padding: '18px 20px',
    background: 'white',
    border: '2px solid #e2e8f0',
    borderRadius: 14,
    cursor: 'pointer',
    transition: 'all 0.2s',
    textAlign: 'left',
  },
  comfortBtnActive: {
    background: '#f0f0ff',
    borderColor: '#6366f1',
  },
  comfortLabel: {
    fontSize: 15,
    fontWeight: 600,
    color: '#1e293b',
  },
  comfortDesc: {
    fontSize: 13,
    color: '#94a3b8',
  },

  // ===========================================
  // COMPLETION NOTE
  // ===========================================
  completionNote: {
    display: 'flex',
    gap: 16,
    padding: 20,
    background: '#ecfdf5',
    borderRadius: 16,
    marginTop: 20,
  },
  completionTitle: {
    fontSize: 15,
    fontWeight: 600,
    color: '#065f46',
    marginBottom: 4,
  },
  completionText: {
    fontSize: 14,
    color: '#047857',
    lineHeight: 1.5,
  },

  // ===========================================
  // CHAT STYLES
  // ===========================================
  chatContainer: {
    minHeight: '100vh',
    background: '#f8fafc',
    maxWidth: 430,
    margin: '0 auto',
    fontFamily: "'DM Sans', -apple-system, BlinkMacSystemFont, sans-serif",
    display: 'flex',
    flexDirection: 'column',
  },
  chatHeader: {
    display: 'flex',
    alignItems: 'center',
    padding: '12px 16px',
    background: 'white',
    borderBottom: '1px solid #f1f5f9',
    gap: 12,
  },
  chatBackBtn: {
    width: 40,
    height: 40,
    borderRadius: 12,
    background: 'transparent',
    border: 'none',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
  },
  chatHeaderCenter: {
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    gap: 12,
  },
  chatAdvisorAvatar: {
    width: 44,
    height: 44,
    borderRadius: 12,
    background: 'linear-gradient(135deg, #ccfbf1 0%, #99f6e4 100%)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  chatAdvisorName: {
    fontSize: 16,
    fontWeight: 600,
    color: '#1e293b',
  },
  chatAdvisorStatus: {
    fontSize: 13,
    color: '#64748b',
    display: 'flex',
    alignItems: 'center',
    gap: 6,
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: '50%',
    background: '#10b981',
  },
  chatMenuBtn: {
    width: 40,
    height: 40,
    borderRadius: 12,
    background: 'transparent',
    border: 'none',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
  },
  chatMessages: {
    flex: 1,
    padding: '16px',
    overflowY: 'auto',
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
  },
  messageWrapper: {
    display: 'flex',
    gap: 10,
    alignItems: 'flex-end',
  },
  messageAvatar: {
    width: 28,
    height: 28,
    borderRadius: 8,
    background: '#ecfdf5',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  messageBubble: {
    maxWidth: '80%',
    padding: '12px 16px',
    borderRadius: 16,
  },
  userBubble: {
    background: 'linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%)',
    borderBottomRightRadius: 4,
    color: 'white',
  },
  advisorBubble: {
    background: 'white',
    borderBottomLeftRadius: 4,
    boxShadow: '0 2px 8px rgba(0,0,0,0.06)',
  },
  messageText: {
    fontSize: 15,
    lineHeight: 1.5,
    margin: 0,
    whiteSpace: 'pre-wrap',
  },
  messageTime: {
    fontSize: 11,
    opacity: 0.7,
    display: 'block',
    marginTop: 6,
  },
  typingIndicator: {
    display: 'flex',
    gap: 4,
    padding: '4px 0',
  },
  typingDot: {
    width: 8,
    height: 8,
    borderRadius: '50%',
    background: '#94a3b8',
    animation: 'pulse 1.4s infinite',
  },
  quickPrompts: {
    padding: '0 16px 16px',
    display: 'flex',
    flexWrap: 'wrap',
    gap: 8,
  },
  quickPromptBtn: {
    padding: '10px 14px',
    background: 'white',
    border: '1px solid #e2e8f0',
    borderRadius: 20,
    fontSize: 13,
    color: '#64748b',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  chatInputArea: {
    padding: '12px 16px 24px',
    background: 'white',
    borderTop: '1px solid #f1f5f9',
  },
  chatInputWrapper: {
    display: 'flex',
    alignItems: 'flex-end',
    gap: 10,
    background: '#f8fafc',
    borderRadius: 16,
    padding: '8px 8px 8px 16px',
  },
  chatInput: {
    flex: 1,
    border: 'none',
    background: 'transparent',
    fontSize: 15,
    resize: 'none',
    outline: 'none',
    fontFamily: 'inherit',
    padding: '8px 0',
    maxHeight: 100,
  },
  chatSendBtn: {
    width: 40,
    height: 40,
    borderRadius: 12,
    background: 'linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%)',
    border: 'none',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    color: 'white',
    flexShrink: 0,
  },
  chatDisclaimer: {
    fontSize: 12,
    color: '#94a3b8',
    textAlign: 'center',
    marginTop: 8,
  },

  // ===========================================
  // ACCOUNT LINKING STYLES
  // ===========================================
  linkingContainer: {
    minHeight: '100vh',
    background: '#f8fafc',
    position: 'relative',
    maxWidth: 430,
    margin: '0 auto',
    fontFamily: "'DM Sans', -apple-system, BlinkMacSystemFont, sans-serif",
  },
  linkingGradient: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 200,
    background: 'linear-gradient(135deg, #e0e7ff 0%, #fae8ff 50%, #fce7f3 100%)',
    zIndex: 0,
  },
  linkingHeader: {
    display: 'flex',
    alignItems: 'center',
    padding: '16px 20px',
    position: 'relative',
    zIndex: 1,
  },
  linkingTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: 17,
    fontWeight: 600,
    color: '#1e293b',
  },
  linkingMain: {
    padding: '20px',
    position: 'relative',
    zIndex: 1,
  },
  linkingIntro: {
    textAlign: 'center',
    paddingTop: 20,
  },
  linkingIconLarge: {
    width: 80,
    height: 80,
    borderRadius: 20,
    background: 'white',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    margin: '0 auto 24px',
    boxShadow: '0 4px 20px rgba(0,0,0,0.08)',
  },
  linkingHeadline: {
    fontSize: 24,
    fontWeight: 700,
    color: '#1e293b',
    marginBottom: 12,
  },
  linkingSubtext: {
    fontSize: 15,
    color: '#64748b',
    lineHeight: 1.6,
    marginBottom: 32,
  },
  trustPoints: {
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
    marginBottom: 32,
    textAlign: 'left',
  },
  trustPoint: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    fontSize: 14,
    color: '#1e293b',
  },
  linkingPrimaryBtn: {
    width: '100%',
    padding: '16px 24px',
    background: 'linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%)',
    border: 'none',
    borderRadius: 14,
    fontSize: 16,
    fontWeight: 600,
    color: 'white',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginBottom: 12,
  },
  linkingSecondaryBtn: {
    width: '100%',
    padding: '16px 24px',
    background: 'transparent',
    border: 'none',
    borderRadius: 14,
    fontSize: 16,
    fontWeight: 600,
    color: '#64748b',
    cursor: 'pointer',
  },
  linkingSelect: {
    paddingTop: 20,
  },
  selectTitle: {
    fontSize: 20,
    fontWeight: 600,
    color: '#1e293b',
    marginBottom: 20,
  },
  searchBox: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    padding: '14px 18px',
    background: 'white',
    borderRadius: 14,
    marginBottom: 20,
    boxShadow: '0 2px 8px rgba(0,0,0,0.06)',
  },
  searchInput: {
    flex: 1,
    border: 'none',
    background: 'transparent',
    fontSize: 15,
    outline: 'none',
  },
  institutionGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: 12,
    marginBottom: 20,
  },
  institutionBtn: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 8,
    padding: '20px',
    background: 'white',
    border: '2px solid #e2e8f0',
    borderRadius: 16,
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  institutionIcon: {
    fontSize: 28,
  },
  institutionName: {
    fontSize: 14,
    fontWeight: 500,
    color: '#1e293b',
    textAlign: 'center',
  },
  institutionHint: {
    fontSize: 13,
    color: '#94a3b8',
    textAlign: 'center',
  },
  linkingConnecting: {
    textAlign: 'center',
    paddingTop: 60,
  },
  connectingSpinner: {
    width: 80,
    height: 80,
    margin: '0 auto 24px',
    position: 'relative',
  },
  spinnerRing: {
    width: '100%',
    height: '100%',
    border: '4px solid #e2e8f0',
    borderTopColor: '#6366f1',
    borderRadius: '50%',
    animation: 'spin 1s linear infinite',
  },
  connectingTitle: {
    fontSize: 20,
    fontWeight: 600,
    color: '#1e293b',
    marginBottom: 8,
  },
  connectingText: {
    fontSize: 15,
    color: '#64748b',
    marginBottom: 32,
  },
  connectingSteps: {
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
    textAlign: 'left',
    maxWidth: 280,
    margin: '0 auto',
  },
  connectingStep: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    fontSize: 14,
    color: '#1e293b',
  },
  stepSpinner: {
    width: 16,
    height: 16,
    border: '2px solid #e2e8f0',
    borderTopColor: '#6366f1',
    borderRadius: '50%',
    animation: 'spin 1s linear infinite',
  },
  stepCircle: {
    width: 16,
    height: 16,
    border: '2px solid #e2e8f0',
    borderRadius: '50%',
  },
  linkingSuccess: {
    textAlign: 'center',
    paddingTop: 40,
  },
  successIcon: {
    width: 80,
    height: 80,
    borderRadius: 40,
    background: '#ecfdf5',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    margin: '0 auto 24px',
  },
  successTitle: {
    fontSize: 22,
    fontWeight: 600,
    color: '#1e293b',
    marginBottom: 8,
  },
  successText: {
    fontSize: 15,
    color: '#64748b',
    marginBottom: 32,
    lineHeight: 1.5,
  },
  connectedAccounts: {
    background: 'white',
    borderRadius: 16,
    padding: 20,
    marginBottom: 24,
    textAlign: 'left',
  },
  connectedLabel: {
    fontSize: 13,
    fontWeight: 600,
    color: '#64748b',
    marginBottom: 16,
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
  },
  connectedAccount: {
    display: 'flex',
    alignItems: 'center',
    gap: 14,
    padding: '12px 0',
    borderBottom: '1px solid #f1f5f9',
  },
  accountIcon: {
    fontSize: 24,
  },
  accountInfo: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
  },
  accountName: {
    fontSize: 15,
    fontWeight: 500,
    color: '#1e293b',
  },
  accountType: {
    fontSize: 13,
    color: '#64748b',
  },

  // ===========================================
  // PLAN VIEW STYLES
  // ===========================================
  priorityCard: {
    background: 'white',
    borderRadius: 20,
    padding: 20,
    marginBottom: 20,
    boxShadow: '0 4px 20px rgba(0,0,0,0.06)',
  },
  priorityHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    marginBottom: 16,
  },
  priorityTitle: {
    fontSize: 15,
    fontWeight: 600,
    color: '#1e293b',
  },
  priorityList: {
    listStyle: 'none',
    padding: 0,
    margin: '0 0 16px 0',
  },
  priorityItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    padding: '12px 0',
    borderBottom: '1px solid #f1f5f9',
    fontSize: 15,
    color: '#1e293b',
  },
  priorityNumber: {
    width: 24,
    height: 24,
    borderRadius: 12,
    background: '#6366f1',
    color: 'white',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 13,
    fontWeight: 600,
  },
  priorityWhy: {
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.6,
    background: '#f8fafc',
    padding: 16,
    borderRadius: 12,
  },
  goalsSection: {
    marginBottom: 24,
  },
  goalsList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
  },
  goalCard: {
    background: 'white',
    borderRadius: 16,
    padding: 20,
    boxShadow: '0 2px 12px rgba(0,0,0,0.06)',
  },
  goalHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    marginBottom: 12,
  },
  goalInfo: {
    flex: 1,
  },
  goalTimeline: {
    fontSize: 13,
    color: '#64748b',
  },
  goalPercent: {
    fontSize: 18,
    fontWeight: 700,
    color: '#6366f1',
  },
  goalProgressBar: {
    height: 8,
    background: '#e2e8f0',
    borderRadius: 4,
    overflow: 'hidden',
    marginBottom: 12,
  },
  goalProgressFill: {
    height: '100%',
    background: 'linear-gradient(90deg, #6366f1 0%, #8b5cf6 100%)',
    borderRadius: 4,
    transition: 'width 0.3s ease',
  },
  goalMeta: {
    display: 'flex',
    justifyContent: 'space-between',
    fontSize: 13,
    color: '#64748b',
  },
  emptyGoals: {
    background: 'white',
    borderRadius: 16,
    padding: 32,
    textAlign: 'center',
    color: '#64748b',
  },
  allocationCard: {
    background: 'white',
    borderRadius: 20,
    padding: 20,
    boxShadow: '0 4px 20px rgba(0,0,0,0.06)',
  },
  allocationList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
    marginBottom: 16,
  },
  allocationItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
  },
  allocationDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
  },
  allocationLabel: {
    flex: 1,
    fontSize: 15,
    color: '#1e293b',
  },
  allocationAmount: {
    fontSize: 15,
    fontWeight: 600,
    color: '#1e293b',
  },
  allocationNote: {
    fontSize: 13,
    color: '#94a3b8',
    fontStyle: 'italic',
  },

  // ===========================================
  // LEARN VIEW STYLES
  // ===========================================
  learnSection: {
    marginBottom: 28,
  },
  learnSectionHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    marginBottom: 16,
  },
  recommendedBadge: {
    fontSize: 12,
    color: '#6366f1',
    background: '#f0f0ff',
    padding: '4px 10px',
    borderRadius: 12,
  },
  lessonsList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
  },
  lessonCard: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: 14,
    padding: 16,
    background: 'white',
    border: 'none',
    borderRadius: 16,
    cursor: 'pointer',
    textAlign: 'left',
    boxShadow: '0 2px 12px rgba(0,0,0,0.06)',
    width: '100%',
  },
  lessonIcon: {
    fontSize: 28,
    flexShrink: 0,
  },
  lessonContent: {
    flex: 1,
  },
  lessonTitle: {
    fontSize: 15,
    fontWeight: 600,
    color: '#1e293b',
    display: 'block',
    marginBottom: 4,
  },
  lessonDescription: {
    fontSize: 13,
    color: '#64748b',
    lineHeight: 1.5,
    display: 'block',
    marginBottom: 8,
  },
  lessonMeta: {
    display: 'flex',
    gap: 12,
  },
  lessonCategory: {
    fontSize: 12,
    color: '#6366f1',
    background: '#f0f0ff',
    padding: '2px 8px',
    borderRadius: 8,
  },
  lessonDuration: {
    fontSize: 12,
    color: '#94a3b8',
  },
  philosophyCard: {
    background: 'linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%)',
    borderRadius: 20,
    padding: 24,
    color: 'white',
  },
  philosophyTitle: {
    fontSize: 17,
    fontWeight: 600,
    marginBottom: 8,
  },
  philosophyText: {
    fontSize: 14,
    lineHeight: 1.6,
    opacity: 0.9,
  },

  // ===========================================
  // PROGRESS VIEW STYLES
  // ===========================================
  progressCard: {
    background: 'white',
    borderRadius: 20,
    padding: 20,
    marginBottom: 20,
    boxShadow: '0 4px 20px rgba(0,0,0,0.06)',
  },
  progressCardHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  progressCardTitle: {
    fontSize: 14,
    color: '#64748b',
  },
  progressTrend: {
    fontSize: 13,
    color: '#10b981',
    display: 'flex',
    alignItems: 'center',
    gap: 4,
  },
  netWorthValue: {
    fontSize: 32,
    fontWeight: 700,
    color: '#1e293b',
    marginBottom: 20,
  },
  chartPlaceholder: {
    display: 'flex',
    alignItems: 'flex-end',
    gap: 8,
    height: 80,
    marginBottom: 8,
  },
  chartBar: {
    flex: 1,
    height: '45%',
    background: 'linear-gradient(180deg, #6366f1 0%, #8b5cf6 100%)',
    borderRadius: 4,
  },
  chartLabels: {
    display: 'flex',
    justifyContent: 'space-between',
    fontSize: 11,
    color: '#94a3b8',
  },
  metricsGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: 12,
    marginBottom: 20,
  },
  metricCard: {
    background: 'white',
    borderRadius: 16,
    padding: 16,
    boxShadow: '0 2px 12px rgba(0,0,0,0.06)',
  },
  metricLabel: {
    fontSize: 13,
    color: '#64748b',
    display: 'block',
    marginBottom: 4,
  },
  metricValue: {
    fontSize: 22,
    fontWeight: 700,
    color: '#1e293b',
    display: 'block',
  },
  metricSub: {
    fontSize: 12,
    color: '#94a3b8',
  },
  milestonesCard: {
    background: 'white',
    borderRadius: 20,
    padding: 20,
    marginBottom: 20,
    boxShadow: '0 4px 20px rgba(0,0,0,0.06)',
  },
  milestonesList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 0,
  },
  milestoneItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 14,
    padding: '14px 0',
    borderBottom: '1px solid #f1f5f9',
  },
  milestoneIconComplete: {
    width: 24,
    height: 24,
    borderRadius: 12,
    background: '#10b981',
    color: 'white',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 12,
    fontWeight: 700,
  },
  milestoneIconPending: {
    width: 24,
    height: 24,
    borderRadius: 12,
    border: '2px solid #e2e8f0',
    color: '#94a3b8',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 12,
  },
  milestoneInfo: {
    flex: 1,
  },
  milestoneName: {
    fontSize: 15,
    fontWeight: 500,
    color: '#1e293b',
    display: 'block',
  },
  milestoneNamePending: {
    fontSize: 15,
    fontWeight: 500,
    color: '#94a3b8',
    display: 'block',
  },
  milestoneDate: {
    fontSize: 13,
    color: '#64748b',
  },
  encouragementCard: {
    background: '#ecfdf5',
    borderRadius: 16,
    padding: 20,
    display: 'flex',
    gap: 16,
    alignItems: 'flex-start',
  },
  encouragementEmoji: {
    fontSize: 24,
  },
  encouragementText: {
    fontSize: 14,
    color: '#047857',
    lineHeight: 1.6,
    margin: 0,
  },
  emptyProgress: {
    textAlign: 'center',
    paddingTop: 60,
  },
  emptyIcon: {
    width: 80,
    height: 80,
    borderRadius: 20,
    background: 'white',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    margin: '0 auto 24px',
    boxShadow: '0 4px 20px rgba(0,0,0,0.08)',
  },
  emptyTitle: {
    fontSize: 20,
    fontWeight: 600,
    color: '#1e293b',
    marginBottom: 8,
  },
  emptyText: {
    fontSize: 15,
    color: '#64748b',
    lineHeight: 1.6,
    marginBottom: 24,
  },
  emptyBtn: {
    padding: '14px 28px',
    background: 'linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%)',
    border: 'none',
    borderRadius: 12,
    fontSize: 15,
    fontWeight: 600,
    color: 'white',
    cursor: 'pointer',
  },

  // ===========================================
  // MESSAGES VIEW STYLES
  // ===========================================
  messagesHeader: {
    display: 'flex',
    alignItems: 'center',
    padding: '16px 20px',
    position: 'relative',
    zIndex: 1,
    background: 'transparent',
  },
  messagesTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: 17,
    fontWeight: 600,
    color: '#1e293b',
  },
  markAllBtn: {
    background: 'none',
    border: 'none',
    fontSize: 14,
    color: '#6366f1',
    cursor: 'pointer',
    fontWeight: 500,
  },
  filterPills: {
    display: 'flex',
    gap: 8,
    padding: '0 20px 16px',
    position: 'relative',
    zIndex: 1,
    overflowX: 'auto',
  },
  filterPill: {
    padding: '8px 16px',
    background: 'rgba(255,255,255,0.7)',
    border: 'none',
    borderRadius: 16,
    fontSize: 14,
    fontWeight: 500,
    color: '#64748b',
    cursor: 'pointer',
    whiteSpace: 'nowrap',
  },
  filterPillActive: {
    background: 'white',
    color: '#6366f1',
    boxShadow: '0 2px 8px rgba(0,0,0,0.08)',
  },
  messagesMain: {
    padding: '0 20px 100px',
    position: 'relative',
    zIndex: 1,
  },
  messagesList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
    marginBottom: 24,
  },
  messageItem: {
    display: 'flex',
    gap: 14,
    padding: 16,
    background: 'white',
    border: 'none',
    borderRadius: 16,
    cursor: 'pointer',
    textAlign: 'left',
    width: '100%',
    position: 'relative',
    boxShadow: '0 2px 8px rgba(0,0,0,0.04)',
  },
  messageItemUnread: {
    background: '#fefefe',
    boxShadow: '0 2px 12px rgba(99, 102, 241, 0.1)',
  },
  messageIcon: {
    fontSize: 24,
    flexShrink: 0,
  },
  messageContent: {
    flex: 1,
    minWidth: 0,
  },
  messageHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 4,
  },
  messageTitle: {
    fontSize: 15,
    color: '#1e293b',
    marginRight: 8,
  },
  messageTime: {
    fontSize: 12,
    color: '#94a3b8',
    flexShrink: 0,
  },
  messagePreview: {
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.5,
    margin: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    display: '-webkit-box',
    WebkitLineClamp: 2,
    WebkitBoxOrient: 'vertical',
  },
  unreadDot: {
    position: 'absolute',
    top: 16,
    right: 16,
    width: 10,
    height: 10,
    background: '#6366f1',
    borderRadius: '50%',
  },
  emptyMessages: {
    textAlign: 'center',
    padding: 40,
    color: '#94a3b8',
  },
  preferencesCard: {
    background: 'white',
    borderRadius: 16,
    padding: 20,
  },
  preferencesTitle: {
    fontSize: 15,
    fontWeight: 600,
    color: '#1e293b',
    marginBottom: 8,
  },
  preferencesText: {
    fontSize: 14,
    color: '#64748b',
    lineHeight: 1.5,
    marginBottom: 16,
  },
  preferencesBtn: {
    padding: '12px 20px',
    background: '#f8fafc',
    border: '1px solid #e2e8f0',
    borderRadius: 10,
    fontSize: 14,
    fontWeight: 500,
    color: '#64748b',
    cursor: 'pointer',
  },
};

export default styles;
